name: hn
channels:
  - conda-forge
dependencies:
  - python=3.11
  - anaconda::sqlalchemy
  - conda-forge::dash
  - anaconda::beautifulsoup4
  - conda-forge::dash-bootstrap-components
  - conda-forge::sqlalchemy-utils
  - conda-forge::appdirs
  - conda-forge::asks
  - numpy
  - conda-forge::trio
  - conda-forge::alive-progress
  - conda-forge::polars
  - conda-forge::pyarrow