name: hn
channels:
  - defaults
dependencies:
  - tzdata
  - pip
  - soupsieve
  - urllib3
  - _openmp_mutex
  - charset-normalizer
  - zipp
  - flask-compress
  - libsqlite
  - cryptography
  - flask
  - click
  - _libgcc_mutex
  - cffi
  - libzlib
  - ncurses
  - tk
  - pysocks
  - requests
  - libuuid
  - libstdcxx-ng
  - libnsl
  - readline
  - brotlipy
  - setuptools
  - wheel
  - libgomp
  - xz
  - certifi
  - pyopenssl
  - dash-bootstrap-components
  - jinja2
  - ld_impl_linux-64
  - bzip2
  - markupsafe
  - plotly
  - idna
  - itsdangerous
  - python_abi
  - pycparser
  - werkzeug
  - brotli-python
  - python=3.11
  - libgcc-ng
  - openssl
  - ca-certificates
  - libffi
  - dash
  - importlib-metadata
  - beautifulsoup4
  - tenacity
  - alive-progress
  - aiohttp
  - cchardet
  - aiodns
  - sqlalchemy-utils
  - appdirs
  - sqlalchemy>=2.0.0
